### ISSUE TITLE
Issues running evogym example

### ISSUE THREAD

**Issue by csvelayutham** [EvolutionGym/evogym-design-tool#7]
Hi,

I installed EvoGym in Linux Mint having Python 3.10. As suggested in the github page I tried to execute the gym_test.py in examples. It issues the following error.

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Using Evolution Gym Simulator v2.2.5
Traceback (most recent call last):
  File "/home/cs_velayutham/Documents/Koding/EvoRo/evogym/examples/gym_test.py", line 9, in <module>
    env = gym.make('Walker-v0', body=body)
  File "/home/cs_velayutham/.local/lib/python3.10/site-packages/gym/envs/registration.py", line 640, in make
    env = env_creator(**_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/evogym-1.0.0-py3.10-linux-x86_64.egg/evogym/envs/walk.py", line 29, in __init__
    self.action_space = spaces.Box(low= 0.6, high=1.6, shape=(num_actuators,), dtype=np.float)
  File "/home/cs_velayutham/.local/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Request for help please

**Comment by csvelayutham** [comment]
Sorry I should have posted in EvoGym rather than here. Posting there ....
